### ISSUE TITLE
hydrogen bonding energy

### ISSUE THREAD

**Issue by thuxugang** [tommyhuangthu/FASPR#1]
Hi, thanks for the great work!
I read your code and found the formula for calculating hydrogen bonding energy (SelfEnergy.cpp line 194 : float fdist=5.*pow(OPT_HBOND_DIST/dist,12)-6.*pow(OPT_HBOND_DIST/dist,10)) is different from the eq (3) in the FASPR paper. Could you please tell me which one should i use to calculate hydrogen bonding energy? Many thanks...
Xu Gang

**Comment by tommyhuangthu** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Hello Gang,
        Thanks for pointing out the problem. The power 6 in the FASPR paper is a typo and it should be 10 as in the source code.Best wishes,Xiaoqiang
    
        
            
        
    
    
         
        
            
    
        font{
            line-height: 1.6;
        }
    
Xiaoqiang Huang, PhDResearch InvestigatorYang Zhang LabUniv. of Michigan Medical SchoolEmail: ***@***.***

        
    
     

    On 3/18/2021 ***@***.***> wrote： 



Hi, thanks for the great work!
I read your code and found the formula for calculating hydrogen bonding energy (SelfEnergy.cpp line 194 : float fdist=5.*pow(OPT_HBOND_DIST/dist,12)-6.*pow(OPT_HBOND_DIST/dist,10)) is different from the eq (3) in the FASPR paper. Could you please tell me which one should i use to calculate hydrogen bonding energy? Many thanks...
Xu Gang

**Comment by thuxugang** [comment]
Thanks!
Another thing is, according to the code, fdist ∝ (5*pow(dist, -12)-6*pow(dist, -10)). But the eq (3) shows fdist ∝ (5*pow(dist, 12)-6*pow(dist, 10). Which one is correct...
Best,
Xu Gang

**Comment by tommyhuangthu** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        The code is correct. Basically the hbond energy takes the form of a lennard-jones potential but the pows are 12 and 10. You can see the vdw potential at eq. 2, row 3 as a reference; they are similar.
        Thanks,Xiaoqiang
    
        
            
        
    
    
         
        
            
    
        font{
            line-height: 1.6;
        }
    
Xiaoqiang Huang, PhDResearch InvestigatorYang Zhang LabUniv. of Michigan Medical SchoolEmail: ***@***.***

        
    
     

    On 3/18/2021 ***@***.***> wrote： 




Thanks!

Another thing is, according to the code, fdist ∝ (5pow(dist, -12)-6pow(dist, -10)). But the eq (3) shows fdist ∝ (5pow(dist, 12)-6pow(dist, 10). Which one is correct...

Best,

Xu Gang

**Comment by thuxugang** [comment]
Thanks for the help!
